import { comfydeploy_hash } from "@/utils/comfydeploy-hash";

export const defaultWorkflowTemplate = {
  name: "sd1.5",
  description: "Text to image with sd 1.5 base model",
  machine_deps: {
    files: {},
    models: {
      checkpoints: [
        {
          hash: "cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516",
          name: "v1-5-pruned-emaonly.ckpt",
        },
      ],
    },
    comfyui: "8dc19e40d129c8ee049be7be2657458509717ba5",
    custom_nodes: {
      "https://github.com/BennyKok/comfyui-deploy": {
        url: "https://github.com/BennyKok/comfyui-deploy",
        hash: comfydeploy_hash,
        name: "ComfyUI Deploy",
        files: ["https://github.com/BennyKok/comfyui-deploy"],
        install_type: "git-clone",
      },
    },
    missing_nodes: [],
  },
  workflow: {
    extra: {},
    links: [
      [1, 4, 0, 3, 0, "MODEL"],
      [2, 5, 0, 3, 3, "LATENT"],
      [3, 4, 1, 6, 0, "CLIP"],
      [4, 6, 0, 3, 1, "CONDITIONING"],
      [5, 4, 1, 7, 0, "CLIP"],
      [6, 7, 0, 3, 2, "CONDITIONING"],
      [7, 3, 0, 8, 0, "LATENT"],
      [8, 4, 2, 8, 1, "VAE"],
      [9, 8, 0, 9, 0, "IMAGE"],
      [10, 12, 0, 6, 1, "STRING"],
      [11, 13, 0, 7, 1, "STRING"],
    ],
    nodes: [
      {
        id: 5,
        pos: [473, 609],
        mode: 0,
        size: { "0": 315, "1": 106 },
        type: "EmptyLatentImage",
        flags: {},
        order: 0,
        outputs: [
          { name: "LATENT", type: "LATENT", links: [2], slot_index: 0 },
        ],
        properties: { "Node name for S&R": "EmptyLatentImage" },
        widgets_values: [512, 512, 1],
      },
      {
        id: 3,
        pos: [863, 186],
        mode: 0,
        size: { "0": 315, "1": 262 },
        type: "KSampler",
        flags: {},
        order: 7,
        inputs: [
          { link: 1, name: "model", type: "MODEL" },
          { link: 4, name: "positive", type: "CONDITIONING" },
          { link: 6, name: "negative", type: "CONDITIONING" },
          { link: 2, name: "latent_image", type: "LATENT" },
        ],
        outputs: [
          { name: "LATENT", type: "LATENT", links: [7], slot_index: 0 },
        ],
        properties: { "Node name for S&R": "KSampler" },
        widgets_values: [
          156680208700286,
          "randomize",
          20,
          8,
          "euler",
          "normal",
          1,
        ],
      },
      {
        id: 8,
        pos: [1209, 188],
        mode: 0,
        size: { "0": 210, "1": 46 },
        type: "VAEDecode",
        flags: {},
        order: 8,
        inputs: [
          { link: 7, name: "samples", type: "LATENT" },
          { link: 8, name: "vae", type: "VAE" },
        ],
        outputs: [{ name: "IMAGE", type: "IMAGE", links: [9], slot_index: 0 }],
        properties: { "Node name for S&R": "VAEDecode" },
      },
      {
        id: 9,
        pos: [1451, 189],
        mode: 0,
        size: { "0": 210, "1": 58 },
        type: "SaveImage",
        flags: {},
        order: 9,
        inputs: [{ link: 9, name: "images", type: "IMAGE" }],
        properties: {},
        widgets_values: ["ComfyUI"],
      },
      {
        id: 4,
        pos: [26, 474],
        mode: 0,
        size: { "0": 315, "1": 98 },
        type: "CheckpointLoaderSimple",
        flags: {},
        order: 1,
        outputs: [
          { name: "MODEL", type: "MODEL", links: [1], slot_index: 0 },
          { name: "CLIP", type: "CLIP", links: [3, 5], slot_index: 1 },
          { name: "VAE", type: "VAE", links: [8], slot_index: 2 },
        ],
        properties: { "Node name for S&R": "CheckpointLoaderSimple" },
        widgets_values: ["v1-5-pruned-emaonly.ckpt"],
      },
      {
        id: 6,
        pos: [415, 186],
        mode: 0,
        size: [422.84503173828125, 164.31304931640625],
        type: "CLIPTextEncode",
        flags: {},
        order: 6,
        inputs: [
          { link: 3, name: "clip", type: "CLIP" },
          {
            link: 10,
            name: "text",
            type: "STRING",
            widget: { name: "text" },
          },
        ],
        outputs: [
          {
            name: "CONDITIONING",
            type: "CONDITIONING",
            links: [4],
            slot_index: 0,
          },
        ],
        properties: { "Node name for S&R": "CLIPTextEncode" },
        widgets_values: [
          "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,",
        ],
      },
      {
        id: 7,
        pos: [413, 389],
        mode: 0,
        size: [425.27801513671875, 180.6060791015625],
        type: "CLIPTextEncode",
        flags: {},
        order: 5,
        inputs: [
          { link: 5, name: "clip", type: "CLIP" },
          {
            link: 11,
            name: "text",
            type: "STRING",
            widget: { name: "text" },
          },
        ],
        outputs: [
          {
            name: "CONDITIONING",
            type: "CONDITIONING",
            links: [6],
            slot_index: 0,
          },
        ],
        properties: { "Node name for S&R": "CLIPTextEncode" },
        widgets_values: ["text, watermark"],
      },
      {
        id: 13,
        pos: [-70, -60],
        mode: 0,
        size: { "0": 400, "1": 200 },
        type: "ComfyUIDeployExternalText",
        flags: {},
        order: 2,
        outputs: [
          {
            name: "text",
            type: "STRING",
            links: [11],
            shape: 3,
            slot_index: 0,
          },
        ],
        properties: { "Node name for S&R": "ComfyUIDeployExternalText" },
        widgets_values: ["negative_prompt", "text, watermark"],
      },
      {
        id: 12,
        pos: [-72, 193],
        mode: 0,
        size: { "0": 400, "1": 200 },
        type: "ComfyUIDeployExternalText",
        flags: {},
        order: 3,
        outputs: [
          {
            name: "text",
            type: "STRING",
            links: [10],
            shape: 3,
            slot_index: 0,
          },
        ],
        properties: { "Node name for S&R": "ComfyUIDeployExternalText" },
        widgets_values: [
          "positive_prompt",
          "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,",
        ],
      },
      {
        id: 14,
        pos: [419, 23],
        mode: 0,
        size: { "0": 210, "1": 96 },
        type: "ComfyDeploy",
        color: "#432",
        flags: {},
        order: 4,
        bgcolor: "#653",
        properties: { version: "", workflow_id: "", workflow_name: "" },
        widgets_values: [
          "Simple SD Template",
          "ccc9debe-bd01-4913-8853-9046738359c7",
          1,
        ],
      },
    ],
    config: {},
    groups: [],
    version: 0.4,
    last_link_id: 11,
    last_node_id: 14,
  },
  workflow_api: {
    "3": {
      inputs: {
        cfg: 8,
        seed: 156680208700286,
        model: ["4", 0],
        steps: 20,
        denoise: 1,
        negative: ["7", 0],
        positive: ["6", 0],
        scheduler: "normal",
        latent_image: ["5", 0],
        sampler_name: "euler",
      },
      class_type: "KSampler",
    },
    "4": {
      inputs: { ckpt_name: "v1-5-pruned-emaonly.ckpt" },
      class_type: "CheckpointLoaderSimple",
    },
    "5": {
      inputs: { width: 512, height: 512, batch_size: 1 },
      class_type: "EmptyLatentImage",
    },
    "6": {
      inputs: { clip: ["4", 1], text: ["12", 0] },
      class_type: "CLIPTextEncode",
    },
    "7": {
      inputs: { clip: ["4", 1], text: ["13", 0] },
      class_type: "CLIPTextEncode",
    },
    "8": {
      inputs: { vae: ["4", 2], samples: ["3", 0] },
      class_type: "VAEDecode",
    },
    "9": {
      inputs: { images: ["8", 0], filename_prefix: "ComfyUI" },
      class_type: "SaveImage",
    },
    "12": {
      inputs: {
        input_id: "positive_prompt",
        default_value:
          "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,",
      },
      class_type: "ComfyUIDeployExternalText",
    },
    "13": {
      inputs: {
        input_id: "negative_prompt",
        default_value: "text, watermark",
      },
      class_type: "ComfyUIDeployExternalText",
    },
  },
};

export type defaultWorkflowTemplateType = {
  workflowId: string;
  workflowName: string;
  workflowDescription: string;
  workflowJson: string;
  workflowApi?: string;
  workflowImageUrl: string;
};

const workflow_json_sd3_5 = {
  last_node_id: 60,
  last_link_id: 110,
  nodes: [
    {
      id: 3,
      type: "KSampler",
      pos: { "0": 864, "1": 96 },
      size: { "0": 315, "1": 262 },
      flags: {},
      order: 15,
      mode: 0,
      inputs: [
        { link: 107, name: "model", type: "MODEL", slot_index: 0 },
        { link: 21, name: "positive", type: "CONDITIONING" },
        { link: 80, name: "negative", type: "CONDITIONING" },
        { link: 100, name: "latent_image", type: "LATENT" },
      ],
      outputs: [{ name: "LATENT", type: "LATENT", links: [7], slot_index: 0 }],
      properties: { "Node name for S&R": "KSampler" },
      widgets_values: [
        844390075629552,
        "randomize",
        20,
        5.45,
        "euler",
        "sgm_uniform",
        1,
      ],
    },
    {
      id: 8,
      type: "VAEDecode",
      pos: { "0": 1200, "1": 96 },
      size: { "0": 210, "1": 46 },
      flags: {},
      order: 16,
      mode: 0,
      inputs: [
        { link: 7, name: "samples", type: "LATENT" },
        { link: 53, name: "vae", type: "VAE", slot_index: 1 },
      ],
      outputs: [{ name: "IMAGE", type: "IMAGE", links: [51], slot_index: 0 }],
      properties: { "Node name for S&R": "VAEDecode" },
      widgets_values: [],
    },
    {
      id: 9,
      type: "SaveImage",
      pos: { "0": 1440, "1": 96 },
      size: { "0": 952.5112915039062, "1": 1007.9328002929688 },
      flags: {},
      order: 17,
      mode: 0,
      inputs: [{ link: 51, name: "images", type: "IMAGE", slot_index: 0 }],
      outputs: [],
      properties: {},
      widgets_values: ["ComfyUI"],
    },
    {
      id: 4,
      type: "CheckpointLoaderSimple",
      pos: { "0": -186, "1": 464 },
      size: { "0": 384.75592041015625, "1": 98 },
      flags: {},
      order: 0,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "MODEL", type: "MODEL", links: [106], slot_index: 0 },
        { name: "CLIP", type: "CLIP", links: [], slot_index: 1 },
        { name: "VAE", type: "VAE", links: [53], slot_index: 2 },
      ],
      properties: { "Node name for S&R": "CheckpointLoaderSimple" },
      widgets_values: ["sd3.5_large.safetensors"],
    },
    {
      id: 16,
      type: "CLIPTextEncode",
      pos: { "0": 384, "1": 87 },
      size: { "0": 432, "1": 192 },
      flags: {},
      order: 14,
      mode: 0,
      inputs: [
        { link: 103, name: "clip", type: "CLIP" },
        { link: 105, name: "text", type: "STRING", widget: { name: "text" } },
      ],
      outputs: [
        {
          name: "CONDITIONING",
          type: "CONDITIONING",
          links: [21],
          slot_index: 0,
        },
      ],
      title: "Positive Prompt",
      properties: { "Node name for S&R": "CLIPTextEncode" },
      widgets_values: [
        "a bottle with a rainbow galaxy inside it on top of a wooden table on a snowy mountain top with the ocean and clouds in the background with a shot glass beside containing darkness beside a snow sculpture in the shape of a fox",
      ],
      color: "#232",
      bgcolor: "#353",
    },
    {
      id: 40,
      type: "CLIPTextEncode",
      pos: { "0": 384, "1": 336 },
      size: { "0": 432, "1": 192 },
      flags: {},
      order: 12,
      mode: 0,
      inputs: [{ link: 104, name: "clip", type: "CLIP" }],
      outputs: [
        {
          name: "CONDITIONING",
          type: "CONDITIONING",
          links: [80],
          shape: 3,
          slot_index: 0,
        },
      ],
      title: "Negative Prompt",
      properties: { "Node name for S&R": "CLIPTextEncode" },
      widgets_values: [""],
      color: "#322",
      bgcolor: "#533",
    },
    {
      id: 41,
      type: "CLIPLoader",
      pos: { "0": -96, "1": 0 },
      size: { "0": 315, "1": 82 },
      flags: {},
      order: 1,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "CLIP", type: "CLIP", links: [], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "CLIPLoader" },
      widgets_values: ["t5xxl_fp16.safetensors", "sd3"],
    },
    {
      id: 42,
      type: "DualCLIPLoader",
      pos: { "0": -96, "1": 144 },
      size: { "0": 315, "1": 106 },
      flags: {},
      order: 2,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "CLIP", type: "CLIP", links: [], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "DualCLIPLoader" },
      widgets_values: ["clip_l.safetensors", "clip_g.safetensors", "sd3"],
    },
    {
      id: 43,
      type: "TripleCLIPLoader",
      pos: { "0": -96, "1": 288 },
      size: { "0": 315, "1": 106 },
      flags: {},
      order: 3,
      mode: 0,
      inputs: [],
      outputs: [
        {
          name: "CLIP",
          type: "CLIP",
          links: [103, 104],
          shape: 3,
          slot_index: 0,
        },
      ],
      properties: { "Node name for S&R": "TripleCLIPLoader" },
      widgets_values: [
        "clip_l.safetensors",
        "clip_g.safetensors",
        "t5xxl_fp16.safetensors",
      ],
    },
    {
      id: 50,
      type: "Note",
      pos: { "0": -384, "1": 144 },
      size: { "0": 223.34756469726562, "1": 254.37765502929688 },
      flags: {},
      order: 4,
      mode: 0,
      inputs: [],
      outputs: [],
      properties: { text: "" },
      widgets_values: [
        "SD3 supports different text encoder configurations, you can see how to load them here.\n\n\nMake sure to put these files:\nclip_g.safetensors\nclip_l.safetensors\nt5xxl_fp16.safetensors\n\n\nIn the ComfyUI/models/clip directory",
      ],
      color: "#432",
      bgcolor: "#653",
    },
    {
      id: 54,
      type: "CheckpointLoaderSimple",
      pos: { "0": -251, "1": 632 },
      size: { "0": 315, "1": 98 },
      flags: {},
      order: 5,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "MODEL", type: "MODEL", links: null },
        { name: "CLIP", type: "CLIP", links: null },
        { name: "VAE", type: "VAE", links: null },
      ],
      properties: { "Node name for S&R": "CheckpointLoaderSimple" },
      widgets_values: ["sd3.5_large.safetensors"],
    },
    {
      id: 57,
      type: "TorchCompileModel",
      pos: { "0": 118, "1": 648 },
      size: { "0": 315, "1": 58 },
      flags: {},
      order: 11,
      mode: 0,
      inputs: [{ link: 106, name: "model", type: "MODEL" }],
      outputs: [
        { name: "MODEL", type: "MODEL", links: [107], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "TorchCompileModel" },
      widgets_values: ["inductor"],
    },
    {
      id: 51,
      type: "Note",
      pos: { "0": -679, "1": 788 },
      size: { "0": 384, "1": 192 },
      flags: {},
      order: 6,
      mode: 0,
      inputs: [],
      outputs: [],
      properties: { text: "" },
      widgets_values: [
        "sd3.5_large.safetensors and sd3.5_medium.safetensors are files that do not contain any CLIP/text encoder weights so you need to load them separately.\n\nThey go in the ComfyUI/models/checkpoints directory.",
      ],
      color: "#432",
      bgcolor: "#653",
    },
    {
      id: 58,
      type: "ComfyUIDeployExternalNumberInt",
      pos: { "0": 409, "1": 837 },
      size: { "0": 400, "1": 200 },
      flags: {},
      order: 7,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "value", type: "INT", links: [108], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "ComfyUIDeployExternalNumberInt" },
      widgets_values: ["batch_size", 1, "", ""],
    },
    {
      id: 59,
      type: "ComfyUIDeployExternalNumberInt",
      pos: { "0": -136, "1": 813 },
      size: { "0": 400, "1": 200 },
      flags: {},
      order: 8,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "value", type: "INT", links: [109], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "ComfyUIDeployExternalNumberInt" },
      widgets_values: ["width", 1024, "", ""],
    },
    {
      id: 53,
      type: "EmptySD3LatentImage",
      pos: { "0": 480, "1": 576 },
      size: { "0": 315, "1": 106 },
      flags: {},
      order: 13,
      mode: 0,
      inputs: [
        {
          link: 108,
          name: "batch_size",
          type: "INT",
          widget: { name: "batch_size" },
          slot_index: 0,
        },
        {
          link: 109,
          name: "width",
          type: "INT",
          widget: { name: "width" },
          slot_index: 1,
        },
        { link: 110, name: "height", type: "INT", widget: { name: "height" } },
      ],
      outputs: [
        {
          name: "LATENT",
          type: "LATENT",
          links: [100],
          shape: 3,
          slot_index: 0,
        },
      ],
      properties: { "Node name for S&R": "EmptySD3LatentImage" },
      widgets_values: [1024, 1024, 1],
    },
    {
      id: 60,
      type: "ComfyUIDeployExternalNumberInt",
      pos: { "0": -135, "1": 1060 },
      size: { "0": 400, "1": 200 },
      flags: {},
      order: 9,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "value", type: "INT", links: [110], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "ComfyUIDeployExternalNumberInt" },
      widgets_values: ["height", 1024, "", ""],
    },
    {
      id: 56,
      type: "ComfyUIDeployExternalText",
      pos: { "0": 398, "1": -178 },
      size: { "0": 400, "1": 200 },
      flags: {},
      order: 10,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "text", type: "STRING", links: [105], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "ComfyUIDeployExternalText" },
      widgets_values: [
        "positive_prompt",
        "a bottle with a rainbow galaxy inside it on top of a wooden table on a snowy mountain top with the ocean and clouds in the background with a shot glass beside containing darkness beside a snow sculpture in the shape of a fox",
        "",
        "",
      ],
    },
  ],
  links: [
    [7, 3, 0, 8, 0, "LATENT"],
    [21, 16, 0, 3, 1, "CONDITIONING"],
    [51, 8, 0, 9, 0, "IMAGE"],
    [53, 4, 2, 8, 1, "VAE"],
    [80, 40, 0, 3, 2, "CONDITIONING"],
    [100, 53, 0, 3, 3, "LATENT"],
    [103, 43, 0, 16, 0, "CLIP"],
    [104, 43, 0, 40, 0, "CLIP"],
    [105, 56, 0, 16, 1, "STRING"],
    [106, 4, 0, 57, 0, "MODEL"],
    [107, 57, 0, 3, 0, "MODEL"],
    [108, 58, 0, 53, 0, "INT"],
    [109, 59, 0, 53, 1, "INT"],
    [110, 60, 0, 53, 2, "INT"],
  ],
  groups: [
    {
      title: "Different Text Encoder Configurations",
      bounding: [-144, -96, 480, 528],
      color: "#3f789e",
      font_size: 24,
      flags: {},
    },
  ],
  config: {},
  extra: {
    ds: {
      scale: 0.6303940863128504,
      offset: [598.250134315755, 248.07657372767616],
    },
  },
  version: 0.4,
};

const workflow_api_sd3_5 = {
  "3": {
    inputs: {
      seed: 844390075629552,
      steps: 20,
      cfg: 5.45,
      sampler_name: "euler",
      scheduler: "sgm_uniform",
      denoise: 1,
      model: ["57", 0],
      positive: ["16", 0],
      negative: ["40", 0],
      latent_image: ["53", 0],
    },
    class_type: "KSampler",
    _meta: { title: "KSampler" },
  },
  "4": {
    inputs: { ckpt_name: "sd3.5_large.safetensors" },
    class_type: "CheckpointLoaderSimple",
    _meta: { title: "Load Checkpoint" },
  },
  "8": {
    inputs: { samples: ["3", 0], vae: ["4", 2] },
    class_type: "VAEDecode",
    _meta: { title: "VAE Decode" },
  },
  "9": {
    inputs: { filename_prefix: "ComfyUI", images: ["8", 0] },
    class_type: "SaveImage",
    _meta: { title: "Save Image" },
  },
  "16": {
    inputs: { text: ["56", 0], clip: ["43", 0] },
    class_type: "CLIPTextEncode",
    _meta: { title: "Positive Prompt" },
  },
  "40": {
    inputs: { text: "", clip: ["43", 0] },
    class_type: "CLIPTextEncode",
    _meta: { title: "Negative Prompt" },
  },
  "41": {
    inputs: { clip_name: "t5xxl_fp16.safetensors", type: "sd3" },
    class_type: "CLIPLoader",
    _meta: { title: "Load CLIP" },
  },
  "42": {
    inputs: {
      clip_name1: "clip_l.safetensors",
      clip_name2: "clip_g.safetensors",
      type: "sd3",
    },
    class_type: "DualCLIPLoader",
    _meta: { title: "DualCLIPLoader" },
  },
  "43": {
    inputs: {
      clip_name1: "clip_l.safetensors",
      clip_name2: "clip_g.safetensors",
      clip_name3: "t5xxl_fp16.safetensors",
    },
    class_type: "TripleCLIPLoader",
    _meta: { title: "TripleCLIPLoader" },
  },
  "53": {
    inputs: { width: ["59", 0], height: ["60", 0], batch_size: ["58", 0] },
    class_type: "EmptySD3LatentImage",
    _meta: { title: "EmptySD3LatentImage" },
  },
  "54": {
    inputs: { ckpt_name: "sd3.5_large.safetensors" },
    class_type: "CheckpointLoaderSimple",
    _meta: { title: "Load Checkpoint" },
  },
  "56": {
    inputs: {
      input_id: "positive_prompt",
      default_value:
        "a bottle with a rainbow galaxy inside it on top of a wooden table on a snowy mountain top with the ocean and clouds in the background with a shot glass beside containing darkness beside a snow sculpture in the shape of a fox",
      display_name: "",
      description: "",
    },
    class_type: "ComfyUIDeployExternalText",
    _meta: { title: "External Text (ComfyUI Deploy)" },
  },
  "57": {
    inputs: { backend: "inductor", model: ["4", 0] },
    class_type: "TorchCompileModel",
    _meta: { title: "TorchCompileModel" },
  },
  "58": {
    inputs: {
      input_id: "batch_size",
      default_value: 1,
      display_name: "",
      description: "",
    },
    class_type: "ComfyUIDeployExternalNumberInt",
    _meta: { title: "External Number Int (ComfyUI Deploy)" },
  },
  "59": {
    inputs: {
      input_id: "width",
      default_value: 1024,
      display_name: "",
      description: "",
    },
    class_type: "ComfyUIDeployExternalNumberInt",
    _meta: { title: "External Number Int (ComfyUI Deploy)" },
  },
  "60": {
    inputs: {
      input_id: "height",
      default_value: 1024,
      display_name: "",
      description: "",
    },
    class_type: "ComfyUIDeployExternalNumberInt",
    _meta: { title: "External Number Int (ComfyUI Deploy)" },
  },
};

const workflow_json_flux = {
  last_node_id: 44,
  last_link_id: 66,
  nodes: [
    {
      id: 8,
      type: "VAEDecode",
      pos: { "0": 861, "1": 39 },
      size: { "0": 210, "1": 46 },
      flags: {},
      order: 15,
      mode: 0,
      inputs: [
        { link: 24, name: "samples", type: "LATENT" },
        { link: 12, name: "vae", type: "VAE" },
      ],
      outputs: [{ name: "IMAGE", type: "IMAGE", links: [9], slot_index: 0 }],
      properties: { "Node name for S&R": "VAEDecode" },
      widgets_values: [],
    },
    {
      id: 9,
      type: "SaveImage",
      pos: { "0": 1423.967529296875, "1": -82.93862915039062 },
      size: { "0": 625.3828125, "1": 895.678466796875 },
      flags: {},
      order: 16,
      mode: 0,
      inputs: [{ link: 9, name: "images", type: "IMAGE" }],
      outputs: [],
      properties: {},
      widgets_values: ["ComfyUI"],
    },
    {
      id: 13,
      type: "SamplerCustomAdvanced",
      pos: { "0": 397, "1": 237 },
      size: { "0": 355.20001220703125, "1": 106 },
      flags: {},
      order: 14,
      mode: 0,
      inputs: [
        { link: 37, name: "noise", type: "NOISE", slot_index: 0 },
        { link: 30, name: "guider", type: "GUIDER", slot_index: 1 },
        { link: 19, name: "sampler", type: "SAMPLER", slot_index: 2 },
        { link: 20, name: "sigmas", type: "SIGMAS", slot_index: 3 },
        { link: 23, name: "latent_image", type: "LATENT", slot_index: 4 },
      ],
      outputs: [
        {
          name: "output",
          type: "LATENT",
          links: [24],
          shape: 3,
          slot_index: 0,
        },
        { name: "denoised_output", type: "LATENT", links: null, shape: 3 },
      ],
      properties: { "Node name for S&R": "SamplerCustomAdvanced" },
      widgets_values: [],
    },
    {
      id: 10,
      type: "VAELoader",
      pos: { "0": 858, "1": 206 },
      size: { "0": 213.376708984375, "1": 58 },
      flags: {},
      order: 0,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "VAE", type: "VAE", links: [12], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "VAELoader" },
      widgets_values: ["ae.sft"],
    },
    {
      id: 16,
      type: "KSamplerSelect",
      pos: { "0": 22, "1": 448 },
      size: { "0": 315, "1": 58 },
      flags: {},
      order: 1,
      mode: 0,
      inputs: [],
      outputs: [{ name: "SAMPLER", type: "SAMPLER", links: [19], shape: 3 }],
      properties: { "Node name for S&R": "KSamplerSelect" },
      widgets_values: ["euler"],
    },
    {
      id: 17,
      type: "BasicScheduler",
      pos: { "0": 24, "1": 108 },
      size: { "0": 315, "1": 106 },
      flags: {},
      order: 13,
      mode: 0,
      inputs: [
        { link: 60, name: "model", type: "MODEL", slot_index: 0 },
        { link: 63, name: "steps", type: "INT", widget: { name: "steps" } },
      ],
      outputs: [{ name: "SIGMAS", type: "SIGMAS", links: [20], shape: 3 }],
      properties: { "Node name for S&R": "BasicScheduler" },
      widgets_values: ["simple", 20, 1],
    },
    {
      id: 25,
      type: "RandomNoise",
      pos: { "0": 18, "1": 289 },
      size: { "0": 315, "1": 82 },
      flags: {},
      order: 2,
      mode: 0,
      inputs: [],
      outputs: [{ name: "NOISE", type: "NOISE", links: [37], shape: 3 }],
      properties: { "Node name for S&R": "RandomNoise" },
      widgets_values: [260806693463621, "randomize"],
    },
    {
      id: 12,
      type: "UNETLoader",
      pos: { "0": -427.300537109375, "1": -59 },
      size: { "0": 315, "1": 82 },
      flags: {},
      order: 3,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "MODEL", type: "MODEL", links: [58], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "UNETLoader" },
      widgets_values: ["flux1-dev.sft", "default"],
    },
    {
      id: 11,
      type: "DualCLIPLoader",
      pos: { "0": -434.300537109375, "1": 229 },
      size: { "0": 318.2269287109375, "1": 106 },
      flags: {},
      order: 4,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "CLIP", type: "CLIP", links: [10], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "DualCLIPLoader" },
      widgets_values: [
        "flux/t5xxl_fp16.safetensors",
        "flux/clip_l.safetensors",
        "flux",
      ],
    },
    {
      id: 22,
      type: "BasicGuider",
      pos: { "0": 23.60865020751953, "1": -30.358915328979492 },
      size: { "0": 271.1177062988281, "1": 46 },
      flags: {},
      order: 12,
      mode: 0,
      inputs: [
        { link: 59, name: "model", type: "MODEL", slot_index: 0 },
        { link: 40, name: "conditioning", type: "CONDITIONING", slot_index: 1 },
      ],
      outputs: [
        {
          name: "GUIDER",
          type: "GUIDER",
          links: [30],
          shape: 3,
          slot_index: 0,
        },
      ],
      properties: { "Node name for S&R": "BasicGuider" },
      widgets_values: [],
    },
    {
      id: 6,
      type: "CLIPTextEncode",
      pos: { "0": -429, "1": 398 },
      size: { "0": 325.6178283691406, "1": 96 },
      flags: {},
      order: 10,
      mode: 0,
      inputs: [
        { link: 10, name: "clip", type: "CLIP" },
        {
          link: 66,
          name: "text",
          type: "STRING",
          widget: { name: "text" },
          slot_index: 1,
        },
      ],
      outputs: [
        {
          name: "CONDITIONING",
          type: "CONDITIONING",
          links: [40],
          slot_index: 0,
        },
      ],
      properties: { "Node name for S&R": "CLIPTextEncode" },
      widgets_values: [
        'A photo of a burger. Realistic National geographic photo, epic, the letters "Comfy Deploy" on the burger, make it rad',
      ],
    },
    {
      id: 5,
      type: "EmptyLatentImage",
      pos: { "0": 18, "1": 588 },
      size: { "0": 315, "1": 106 },
      flags: {},
      order: 5,
      mode: 0,
      inputs: [],
      outputs: [{ name: "LATENT", type: "LATENT", links: [23], slot_index: 0 }],
      properties: { "Node name for S&R": "EmptyLatentImage" },
      widgets_values: [1024, 1024, 1],
    },
    {
      id: 43,
      type: "ComfyUIDeployExternalText",
      pos: { "0": -1002, "1": -65 },
      size: { "0": 400, "1": 200 },
      flags: {},
      order: 6,
      mode: 0,
      inputs: [],
      outputs: [{ name: "text", type: "STRING", links: [66], shape: 3 }],
      properties: { "Node name for S&R": "ComfyUIDeployExternalText" },
      widgets_values: [
        "positive_prompt",
        'A photo of a burger. Realistic National geographic photo, epic, the letters "Comfy Deploy" on the burger, make it rad',
        "",
        "",
      ],
    },
    {
      id: 36,
      type: "ComfyUIDeployExternalNumberSlider",
      pos: { "0": -1036, "1": 931 },
      size: { "0": 400, "1": 200 },
      flags: { collapsed: false },
      order: 7,
      mode: 2,
      inputs: [],
      outputs: [
        { name: "value", type: "FLOAT", links: [61], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "ComfyUIDeployExternalNumberSlider" },
      widgets_values: ["lora_strength", 0.5, 0, 1, "", ""],
    },
    {
      id: 35,
      type: "LoraLoaderModelOnly",
      pos: { "0": -428, "1": 92 },
      size: { "0": 315, "1": 82 },
      flags: {},
      order: 11,
      mode: 4,
      inputs: [
        { link: 58, name: "model", type: "MODEL" },
        {
          link: 61,
          name: "strength_model",
          type: "FLOAT",
          widget: { name: "strength_model" },
        },
      ],
      outputs: [
        {
          name: "MODEL",
          type: "MODEL",
          links: [59, 60],
          shape: 3,
          slot_index: 0,
        },
      ],
      properties: { "Node name for S&R": "LoraLoaderModelOnly" },
      widgets_values: [
        "SDXL-Lightning/sdxl_lightning_2step_lora.safetensors",
        1,
      ],
    },
    {
      id: 38,
      type: "ComfyUIDeployExternalNumberInt",
      pos: { "0": -1033, "1": 657 },
      size: { "0": 400, "1": 200 },
      flags: { collapsed: false },
      order: 8,
      mode: 0,
      inputs: [],
      outputs: [
        { name: "value", type: "INT", links: [63], shape: 3, slot_index: 0 },
      ],
      properties: { "Node name for S&R": "ComfyUIDeployExternalNumberInt" },
      widgets_values: ["steps", 20, "", ""],
    },
    {
      id: 44,
      type: "Note",
      pos: { "0": -594, "1": 921 },
      size: { "0": 210, "1": 58 },
      flags: {},
      order: 9,
      mode: 0,
      inputs: [],
      outputs: [],
      properties: { text: "" },
      widgets_values: ["Uncomment this if you need to add a lora "],
      color: "#432",
      bgcolor: "#653",
    },
  ],
  links: [
    [9, 8, 0, 9, 0, "IMAGE"],
    [10, 11, 0, 6, 0, "CLIP"],
    [12, 10, 0, 8, 1, "VAE"],
    [19, 16, 0, 13, 2, "SAMPLER"],
    [20, 17, 0, 13, 3, "SIGMAS"],
    [23, 5, 0, 13, 4, "LATENT"],
    [24, 13, 0, 8, 0, "LATENT"],
    [30, 22, 0, 13, 1, "GUIDER"],
    [37, 25, 0, 13, 0, "NOISE"],
    [40, 6, 0, 22, 1, "CONDITIONING"],
    [58, 12, 0, 35, 0, "MODEL"],
    [59, 35, 0, 22, 0, "MODEL"],
    [60, 35, 0, 17, 0, "MODEL"],
    [61, 36, 0, 35, 1, "FLOAT"],
    [63, 38, 0, 17, 1, "INT"],
    [66, 43, 0, 6, 1, "STRING"],
  ],
  groups: [
    {
      title: "Prompt Input",
      bounding: [-1074, -171, 539, 372],
      color: "#3f789e",
      font_size: 24,
      flags: {},
    },
    {
      title: "Loading Models",
      bounding: [-473, -169, 411, 694],
      color: "#3f789e",
      font_size: 24,
      flags: {},
    },
    {
      title: "Advance Settings",
      bounding: [-1061, 566, 537, 624],
      color: "#3f789e",
      font_size: 24,
      flags: {},
    },
    {
      title: "Decoding Image",
      bounding: [807, -161, 319, 565],
      color: "#3f789e",
      font_size: 24,
      flags: {},
    },
    {
      title: "Sampling Process",
      bounding: [-12, -170, 790, 909],
      color: "#3f789e",
      font_size: 24,
      flags: {},
    },
  ],
  config: {},
  extra: {
    ds: {
      scale: 0.520986848192464,
      offset: [1181.6155172897363, 380.6033930342139],
    },
  },
  version: 0.4,
};

const workflow_api_flux = {
  "5": {
    inputs: { width: 1024, height: 1024, batch_size: 1 },
    class_type: "EmptyLatentImage",
    _meta: { title: "Empty Latent Image" },
  },
  "6": {
    inputs: { text: ["43", 0], clip: ["11", 0] },
    class_type: "CLIPTextEncode",
    _meta: { title: "CLIP Text Encode (Prompt)" },
  },
  "8": {
    inputs: { samples: ["13", 0], vae: ["10", 0] },
    class_type: "VAEDecode",
    _meta: { title: "VAE Decode" },
  },
  "9": {
    inputs: { filename_prefix: "ComfyUI", images: ["8", 0] },
    class_type: "SaveImage",
    _meta: { title: "Save Image" },
  },
  "10": {
    inputs: { vae_name: "ae.sft" },
    class_type: "VAELoader",
    _meta: { title: "Load VAE" },
  },
  "11": {
    inputs: {
      clip_name1: "flux/t5xxl_fp16.safetensors",
      clip_name2: "flux/clip_l.safetensors",
      type: "flux",
    },
    class_type: "DualCLIPLoader",
    _meta: { title: "DualCLIPLoader" },
  },
  "12": {
    inputs: { unet_name: "flux1-dev.sft", weight_dtype: "default" },
    class_type: "UNETLoader",
    _meta: { title: "Load Diffusion Model" },
  },
  "13": {
    inputs: {
      noise: ["25", 0],
      guider: ["22", 0],
      sampler: ["16", 0],
      sigmas: ["17", 0],
      latent_image: ["5", 0],
    },
    class_type: "SamplerCustomAdvanced",
    _meta: { title: "SamplerCustomAdvanced" },
  },
  "16": {
    inputs: { sampler_name: "euler" },
    class_type: "KSamplerSelect",
    _meta: { title: "KSamplerSelect" },
  },
  "17": {
    inputs: {
      scheduler: "simple",
      steps: ["38", 0],
      denoise: 1,
      model: ["12", 0],
    },
    class_type: "BasicScheduler",
    _meta: { title: "BasicScheduler" },
  },
  "22": {
    inputs: { model: ["12", 0], conditioning: ["6", 0] },
    class_type: "BasicGuider",
    _meta: { title: "BasicGuider" },
  },
  "25": {
    inputs: { noise_seed: 260806693463621 },
    class_type: "RandomNoise",
    _meta: { title: "RandomNoise" },
  },
  "38": {
    inputs: {
      input_id: "steps",
      default_value: 20,
      display_name: "",
      description: "",
    },
    class_type: "ComfyUIDeployExternalNumberInt",
    _meta: { title: "External Number Int (ComfyUI Deploy)" },
  },
  "43": {
    inputs: {
      input_id: "positive_prompt",
      default_value:
        'A photo of a burger. Realistic National geographic photo, epic, the letters "Comfy Deploy" on the burger, make it rad',
      display_name: "",
      description: "",
    },
    class_type: "ComfyUIDeployExternalText",
    _meta: { title: "External Text (ComfyUI Deploy)" },
  },
};

export const defaultWorkflowTemplates: defaultWorkflowTemplateType[] = [
  {
    workflowId: "sd1.5",
    workflowName: "Stable Diffusion v1.5",
    workflowDescription: "Text to image with sd 1.5 base model. ",
    workflowJson: JSON.stringify(defaultWorkflowTemplate.workflow),
    workflowApi: JSON.stringify(defaultWorkflowTemplate.workflow_api),
    workflowImageUrl:
      "https://comfy-deploy-output.s3.amazonaws.com/outputs/runs/ae92370b-315a-4578-af29-ed83b00828d1/ComfyUI_00001_.png",
  },
  {
    workflowId: "sd3.5",
    workflowName: "Stable Diffusion v3.5",
    workflowDescription: "Text to image with latest sd 3.5 model.",
    workflowJson: JSON.stringify(workflow_json_sd3_5),
    workflowApi: JSON.stringify(workflow_api_sd3_5),
    workflowImageUrl:
      "https://comfy-deploy-output.s3.amazonaws.com/outputs/runs/36febfce-3cb6-4220-9447-33003e58d381/ComfyUI_00001_.png",
  },
  {
    workflowId: "flux",
    workflowName: "Flux",
    workflowDescription:
      "Text to image with Flux model, most popular and stunning model.",
    workflowApi: JSON.stringify(workflow_api_flux),
    workflowJson: JSON.stringify(workflow_json_flux),
    workflowImageUrl:
      "https://cd-misc.s3.us-east-2.amazonaws.com/templates/1zsngynnMzX8g1FWs61ti.png",
  },
];
