/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WaitlistImport } from './routes/waitlist'
import { Route as UsageImport } from './routes/usage'
import { Route as SettingsImport } from './routes/settings'
import { Route as SecretsImport } from './routes/secrets'
import { Route as PricingImport } from './routes/pricing'
import { Route as OrgNotFoundImport } from './routes/org-not-found'
import { Route as OnboardingCallImport } from './routes/onboarding-call'
import { Route as ModelsImport } from './routes/models'
import { Route as CreateOrgImport } from './routes/create-org'
import { Route as AssetsImport } from './routes/assets'
import { Route as ApiKeysImport } from './routes/api-keys'
import { Route as IndexImport } from './routes/index'
import { Route as WorkflowsIndexImport } from './routes/workflows/index'
import { Route as SessionsIndexImport } from './routes/sessions/index'
import { Route as OrganizationProfileIndexImport } from './routes/organization-profile/index'
import { Route as MachinesIndexImport } from './routes/machines/index'
import { Route as AnalyticsIndexImport } from './routes/analytics/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as SessionsSessionIdIndexImport } from './routes/sessions/$sessionId/index'
import { Route as OrganizationProfileOrganizationMembersIndexImport } from './routes/organization-profile/organization-members/index'
import { Route as MachinesMachineIdIndexImport } from './routes/machines/$machineId/index'
import { Route as WorkflowsWorkflowIdViewImport } from './routes/workflows/$workflowId/$view'
import { Route as ShareUserSlugImport } from './routes/share/$user/$slug'
import { Route as MachinesMachineIdFilesImport } from './routes/machines/$machineId/files'
import { Route as MachinesMachineIdActivityImport } from './routes/machines/$machineId/activity'
import { Route as MachinesMachineIdMachineVersionIdImport } from './routes/machines/$machineId/$machineVersionId'
import { Route as MachinesMachineIdHistoryIndexImport } from './routes/machines/$machineId/history/index'
import { Route as AuthRequestRequestIdIndexImport } from './routes/auth/request/$requestId/index'

// Create/Update Routes

const WaitlistRoute = WaitlistImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRoute,
} as any)

const UsageRoute = UsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SecretsRoute = SecretsImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const OrgNotFoundRoute = OrgNotFoundImport.update({
  id: '/org-not-found',
  path: '/org-not-found',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingCallRoute = OnboardingCallImport.update({
  id: '/onboarding-call',
  path: '/onboarding-call',
  getParentRoute: () => rootRoute,
} as any)

const ModelsRoute = ModelsImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRoute,
} as any)

const CreateOrgRoute = CreateOrgImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRoute,
} as any)

const AssetsRoute = AssetsImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRoute,
} as any)

const ApiKeysRoute = ApiKeysImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowsIndexRoute = WorkflowsIndexImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/workflows/index.lazy').then((d) => d.Route),
)

const SessionsIndexRoute = SessionsIndexImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationProfileIndexRoute = OrganizationProfileIndexImport.update({
  id: '/organization-profile/',
  path: '/organization-profile/',
  getParentRoute: () => rootRoute,
} as any)

const MachinesIndexRoute = MachinesIndexImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsIndexRoute = AnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/analytics/index.lazy').then((d) => d.Route),
)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const SessionsSessionIdIndexRoute = SessionsSessionIdIndexImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationProfileOrganizationMembersIndexRoute =
  OrganizationProfileOrganizationMembersIndexImport.update({
    id: '/organization-profile/organization-members/',
    path: '/organization-profile/organization-members/',
    getParentRoute: () => rootRoute,
  } as any)

const MachinesMachineIdIndexRoute = MachinesMachineIdIndexImport.update({
  id: '/machines/$machineId/',
  path: '/machines/$machineId/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowsWorkflowIdViewRoute = WorkflowsWorkflowIdViewImport.update({
  id: '/workflows/$workflowId/$view',
  path: '/workflows/$workflowId/$view',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/workflows/$workflowId/$view.lazy').then((d) => d.Route),
)

const ShareUserSlugRoute = ShareUserSlugImport.update({
  id: '/share/$user/$slug',
  path: '/share/$user/$slug',
  getParentRoute: () => rootRoute,
} as any)

const MachinesMachineIdFilesRoute = MachinesMachineIdFilesImport.update({
  id: '/machines/$machineId/files',
  path: '/machines/$machineId/files',
  getParentRoute: () => rootRoute,
} as any)

const MachinesMachineIdActivityRoute = MachinesMachineIdActivityImport.update({
  id: '/machines/$machineId/activity',
  path: '/machines/$machineId/activity',
  getParentRoute: () => rootRoute,
} as any)

const MachinesMachineIdMachineVersionIdRoute =
  MachinesMachineIdMachineVersionIdImport.update({
    id: '/machines/$machineId/$machineVersionId',
    path: '/machines/$machineId/$machineVersionId',
    getParentRoute: () => rootRoute,
  } as any)

const MachinesMachineIdHistoryIndexRoute =
  MachinesMachineIdHistoryIndexImport.update({
    id: '/machines/$machineId/history/',
    path: '/machines/$machineId/history/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthRequestRequestIdIndexRoute = AuthRequestRequestIdIndexImport.update({
  id: '/auth/request/$requestId/',
  path: '/auth/request/$requestId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysImport
      parentRoute: typeof rootRoute
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsImport
      parentRoute: typeof rootRoute
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgImport
      parentRoute: typeof rootRoute
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsImport
      parentRoute: typeof rootRoute
    }
    '/onboarding-call': {
      id: '/onboarding-call'
      path: '/onboarding-call'
      fullPath: '/onboarding-call'
      preLoaderRoute: typeof OnboardingCallImport
      parentRoute: typeof rootRoute
    }
    '/org-not-found': {
      id: '/org-not-found'
      path: '/org-not-found'
      fullPath: '/org-not-found'
      preLoaderRoute: typeof OrgNotFoundImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageImport
      parentRoute: typeof rootRoute
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexImport
      parentRoute: typeof rootRoute
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesIndexImport
      parentRoute: typeof rootRoute
    }
    '/organization-profile/': {
      id: '/organization-profile/'
      path: '/organization-profile'
      fullPath: '/organization-profile'
      preLoaderRoute: typeof OrganizationProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsIndexImport
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId/$machineVersionId': {
      id: '/machines/$machineId/$machineVersionId'
      path: '/machines/$machineId/$machineVersionId'
      fullPath: '/machines/$machineId/$machineVersionId'
      preLoaderRoute: typeof MachinesMachineIdMachineVersionIdImport
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId/activity': {
      id: '/machines/$machineId/activity'
      path: '/machines/$machineId/activity'
      fullPath: '/machines/$machineId/activity'
      preLoaderRoute: typeof MachinesMachineIdActivityImport
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId/files': {
      id: '/machines/$machineId/files'
      path: '/machines/$machineId/files'
      fullPath: '/machines/$machineId/files'
      preLoaderRoute: typeof MachinesMachineIdFilesImport
      parentRoute: typeof rootRoute
    }
    '/share/$user/$slug': {
      id: '/share/$user/$slug'
      path: '/share/$user/$slug'
      fullPath: '/share/$user/$slug'
      preLoaderRoute: typeof ShareUserSlugImport
      parentRoute: typeof rootRoute
    }
    '/workflows/$workflowId/$view': {
      id: '/workflows/$workflowId/$view'
      path: '/workflows/$workflowId/$view'
      fullPath: '/workflows/$workflowId/$view'
      preLoaderRoute: typeof WorkflowsWorkflowIdViewImport
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId/': {
      id: '/machines/$machineId/'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/organization-profile/organization-members/': {
      id: '/organization-profile/organization-members/'
      path: '/organization-profile/organization-members'
      fullPath: '/organization-profile/organization-members'
      preLoaderRoute: typeof OrganizationProfileOrganizationMembersIndexImport
      parentRoute: typeof rootRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/request/$requestId/': {
      id: '/auth/request/$requestId/'
      path: '/auth/request/$requestId'
      fullPath: '/auth/request/$requestId'
      preLoaderRoute: typeof AuthRequestRequestIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/machines/$machineId/history/': {
      id: '/machines/$machineId/history/'
      path: '/machines/$machineId/history'
      fullPath: '/machines/$machineId/history'
      preLoaderRoute: typeof MachinesMachineIdHistoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/assets': typeof AssetsRoute
  '/create-org': typeof CreateOrgRoute
  '/models': typeof ModelsRoute
  '/onboarding-call': typeof OnboardingCallRoute
  '/org-not-found': typeof OrgNotFoundRoute
  '/pricing': typeof PricingRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/machines': typeof MachinesIndexRoute
  '/organization-profile': typeof OrganizationProfileIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/machines/$machineId/$machineVersionId': typeof MachinesMachineIdMachineVersionIdRoute
  '/machines/$machineId/activity': typeof MachinesMachineIdActivityRoute
  '/machines/$machineId/files': typeof MachinesMachineIdFilesRoute
  '/share/$user/$slug': typeof ShareUserSlugRoute
  '/workflows/$workflowId/$view': typeof WorkflowsWorkflowIdViewRoute
  '/machines/$machineId': typeof MachinesMachineIdIndexRoute
  '/organization-profile/organization-members': typeof OrganizationProfileOrganizationMembersIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/auth/request/$requestId': typeof AuthRequestRequestIdIndexRoute
  '/machines/$machineId/history': typeof MachinesMachineIdHistoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/assets': typeof AssetsRoute
  '/create-org': typeof CreateOrgRoute
  '/models': typeof ModelsRoute
  '/onboarding-call': typeof OnboardingCallRoute
  '/org-not-found': typeof OrgNotFoundRoute
  '/pricing': typeof PricingRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/machines': typeof MachinesIndexRoute
  '/organization-profile': typeof OrganizationProfileIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/machines/$machineId/$machineVersionId': typeof MachinesMachineIdMachineVersionIdRoute
  '/machines/$machineId/activity': typeof MachinesMachineIdActivityRoute
  '/machines/$machineId/files': typeof MachinesMachineIdFilesRoute
  '/share/$user/$slug': typeof ShareUserSlugRoute
  '/workflows/$workflowId/$view': typeof WorkflowsWorkflowIdViewRoute
  '/machines/$machineId': typeof MachinesMachineIdIndexRoute
  '/organization-profile/organization-members': typeof OrganizationProfileOrganizationMembersIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/auth/request/$requestId': typeof AuthRequestRequestIdIndexRoute
  '/machines/$machineId/history': typeof MachinesMachineIdHistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/assets': typeof AssetsRoute
  '/create-org': typeof CreateOrgRoute
  '/models': typeof ModelsRoute
  '/onboarding-call': typeof OnboardingCallRoute
  '/org-not-found': typeof OrgNotFoundRoute
  '/pricing': typeof PricingRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/machines/': typeof MachinesIndexRoute
  '/organization-profile/': typeof OrganizationProfileIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/machines/$machineId/$machineVersionId': typeof MachinesMachineIdMachineVersionIdRoute
  '/machines/$machineId/activity': typeof MachinesMachineIdActivityRoute
  '/machines/$machineId/files': typeof MachinesMachineIdFilesRoute
  '/share/$user/$slug': typeof ShareUserSlugRoute
  '/workflows/$workflowId/$view': typeof WorkflowsWorkflowIdViewRoute
  '/machines/$machineId/': typeof MachinesMachineIdIndexRoute
  '/organization-profile/organization-members/': typeof OrganizationProfileOrganizationMembersIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/auth/request/$requestId/': typeof AuthRequestRequestIdIndexRoute
  '/machines/$machineId/history/': typeof MachinesMachineIdHistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/assets'
    | '/create-org'
    | '/models'
    | '/onboarding-call'
    | '/org-not-found'
    | '/pricing'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/waitlist'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/analytics'
    | '/machines'
    | '/organization-profile'
    | '/sessions'
    | '/workflows'
    | '/machines/$machineId/$machineVersionId'
    | '/machines/$machineId/activity'
    | '/machines/$machineId/files'
    | '/share/$user/$slug'
    | '/workflows/$workflowId/$view'
    | '/machines/$machineId'
    | '/organization-profile/organization-members'
    | '/sessions/$sessionId'
    | '/auth/request/$requestId'
    | '/machines/$machineId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/assets'
    | '/create-org'
    | '/models'
    | '/onboarding-call'
    | '/org-not-found'
    | '/pricing'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/waitlist'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/analytics'
    | '/machines'
    | '/organization-profile'
    | '/sessions'
    | '/workflows'
    | '/machines/$machineId/$machineVersionId'
    | '/machines/$machineId/activity'
    | '/machines/$machineId/files'
    | '/share/$user/$slug'
    | '/workflows/$workflowId/$view'
    | '/machines/$machineId'
    | '/organization-profile/organization-members'
    | '/sessions/$sessionId'
    | '/auth/request/$requestId'
    | '/machines/$machineId/history'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/assets'
    | '/create-org'
    | '/models'
    | '/onboarding-call'
    | '/org-not-found'
    | '/pricing'
    | '/secrets'
    | '/settings'
    | '/usage'
    | '/waitlist'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/analytics/'
    | '/machines/'
    | '/organization-profile/'
    | '/sessions/'
    | '/workflows/'
    | '/machines/$machineId/$machineVersionId'
    | '/machines/$machineId/activity'
    | '/machines/$machineId/files'
    | '/share/$user/$slug'
    | '/workflows/$workflowId/$view'
    | '/machines/$machineId/'
    | '/organization-profile/organization-members/'
    | '/sessions/$sessionId/'
    | '/auth/request/$requestId/'
    | '/machines/$machineId/history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AssetsRoute: typeof AssetsRoute
  CreateOrgRoute: typeof CreateOrgRoute
  ModelsRoute: typeof ModelsRoute
  OnboardingCallRoute: typeof OnboardingCallRoute
  OrgNotFoundRoute: typeof OrgNotFoundRoute
  PricingRoute: typeof PricingRoute
  SecretsRoute: typeof SecretsRoute
  SettingsRoute: typeof SettingsRoute
  UsageRoute: typeof UsageRoute
  WaitlistRoute: typeof WaitlistRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  OrganizationProfileIndexRoute: typeof OrganizationProfileIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  MachinesMachineIdMachineVersionIdRoute: typeof MachinesMachineIdMachineVersionIdRoute
  MachinesMachineIdActivityRoute: typeof MachinesMachineIdActivityRoute
  MachinesMachineIdFilesRoute: typeof MachinesMachineIdFilesRoute
  ShareUserSlugRoute: typeof ShareUserSlugRoute
  WorkflowsWorkflowIdViewRoute: typeof WorkflowsWorkflowIdViewRoute
  MachinesMachineIdIndexRoute: typeof MachinesMachineIdIndexRoute
  OrganizationProfileOrganizationMembersIndexRoute: typeof OrganizationProfileOrganizationMembersIndexRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  AuthRequestRequestIdIndexRoute: typeof AuthRequestRequestIdIndexRoute
  MachinesMachineIdHistoryIndexRoute: typeof MachinesMachineIdHistoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  AssetsRoute: AssetsRoute,
  CreateOrgRoute: CreateOrgRoute,
  ModelsRoute: ModelsRoute,
  OnboardingCallRoute: OnboardingCallRoute,
  OrgNotFoundRoute: OrgNotFoundRoute,
  PricingRoute: PricingRoute,
  SecretsRoute: SecretsRoute,
  SettingsRoute: SettingsRoute,
  UsageRoute: UsageRoute,
  WaitlistRoute: WaitlistRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  OrganizationProfileIndexRoute: OrganizationProfileIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  MachinesMachineIdMachineVersionIdRoute:
    MachinesMachineIdMachineVersionIdRoute,
  MachinesMachineIdActivityRoute: MachinesMachineIdActivityRoute,
  MachinesMachineIdFilesRoute: MachinesMachineIdFilesRoute,
  ShareUserSlugRoute: ShareUserSlugRoute,
  WorkflowsWorkflowIdViewRoute: WorkflowsWorkflowIdViewRoute,
  MachinesMachineIdIndexRoute: MachinesMachineIdIndexRoute,
  OrganizationProfileOrganizationMembersIndexRoute:
    OrganizationProfileOrganizationMembersIndexRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  AuthRequestRequestIdIndexRoute: AuthRequestRequestIdIndexRoute,
  MachinesMachineIdHistoryIndexRoute: MachinesMachineIdHistoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/api-keys",
        "/assets",
        "/create-org",
        "/models",
        "/onboarding-call",
        "/org-not-found",
        "/pricing",
        "/secrets",
        "/settings",
        "/usage",
        "/waitlist",
        "/auth/sign-in",
        "/auth/sign-up",
        "/analytics/",
        "/machines/",
        "/organization-profile/",
        "/sessions/",
        "/workflows/",
        "/machines/$machineId/$machineVersionId",
        "/machines/$machineId/activity",
        "/machines/$machineId/files",
        "/share/$user/$slug",
        "/workflows/$workflowId/$view",
        "/machines/$machineId/",
        "/organization-profile/organization-members/",
        "/sessions/$sessionId/",
        "/auth/request/$requestId/",
        "/machines/$machineId/history/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/api-keys": {
      "filePath": "api-keys.tsx"
    },
    "/assets": {
      "filePath": "assets.tsx"
    },
    "/create-org": {
      "filePath": "create-org.tsx"
    },
    "/models": {
      "filePath": "models.tsx"
    },
    "/onboarding-call": {
      "filePath": "onboarding-call.tsx"
    },
    "/org-not-found": {
      "filePath": "org-not-found.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/secrets": {
      "filePath": "secrets.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/usage": {
      "filePath": "usage.tsx"
    },
    "/waitlist": {
      "filePath": "waitlist.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/analytics/": {
      "filePath": "analytics/index.tsx"
    },
    "/machines/": {
      "filePath": "machines/index.tsx"
    },
    "/organization-profile/": {
      "filePath": "organization-profile/index.tsx"
    },
    "/sessions/": {
      "filePath": "sessions/index.tsx"
    },
    "/workflows/": {
      "filePath": "workflows/index.tsx"
    },
    "/machines/$machineId/$machineVersionId": {
      "filePath": "machines/$machineId/$machineVersionId.tsx"
    },
    "/machines/$machineId/activity": {
      "filePath": "machines/$machineId/activity.tsx"
    },
    "/machines/$machineId/files": {
      "filePath": "machines/$machineId/files.tsx"
    },
    "/share/$user/$slug": {
      "filePath": "share/$user/$slug.tsx"
    },
    "/workflows/$workflowId/$view": {
      "filePath": "workflows/$workflowId/$view.tsx"
    },
    "/machines/$machineId/": {
      "filePath": "machines/$machineId/index.tsx"
    },
    "/organization-profile/organization-members/": {
      "filePath": "organization-profile/organization-members/index.tsx"
    },
    "/sessions/$sessionId/": {
      "filePath": "sessions/$sessionId/index.tsx"
    },
    "/auth/request/$requestId/": {
      "filePath": "auth/request/$requestId/index.tsx"
    },
    "/machines/$machineId/history/": {
      "filePath": "machines/$machineId/history/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
